### ISSUE TITLE
Detect Recursive References

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/containers#10]
## The Problem
It can happen that during resolution of a service, its own definition gets invoked. In these cases, it can become quite hard to debug by looking at just a stack trace.

## Suggested Solution
Implement recursion detection, such that an exception is thrown if a service definition invokes itself, directly or not.

**Comment by mecha** [comment]
What a coincidence, I literally implemented this detection last Friday. I can share my solution if you want.

**Comment by XedinUnknown** [comment]
I would love that!

**Comment by mecha** [comment]
```php
public function get($id)
{
    static $fetching = [];

    if (isset($fetching[$id])) {
        $trace = $this->getFetchTrace($fetching);

        throw new LogicException(
			"Circular dependency detected for \"${id}\":\n{$trace}"
		);
    }

    $fetching[$id] = true;

    try {
        return $this->actualGet($id);
    } catch (ContainerExceptionInterface $exception) {
        throw $exception;
    } finally {
        unset($fetching[$id]);
    }
}

protected function getFetchTrace(array $fetched)
{
	$keys = array_reverse(array_keys($fetched));

	$i = 0;
	$trace = array_map(function ($id) use (&$i) {
		$i++;
		return "required by: {$id}";
    }, $keys);

	return implode("\n", $trace);
}
```

**Comment by XedinUnknown** [comment]
I, uh, thought that this would come in the form of a PR, to be honest :D

**Comment by mecha** [comment]
I'll get around it eventually.

**Comment by mecha** [comment]
> I'll get around it eventually.

... aaaaaand I never did

**Comment by mecha** [comment]
> > I'll get around it eventually.

> ... aaaaaand I never did

Until now :wink:
