### ISSUE TITLE
Missing return type

### ISSUE THREAD

**Issue by strangerkir** [Dhii/containers#24]
Hey :) Here is missing return type in the `Dhii\Container\Dictionary::getIterator()`. [Here](https://github.com/Dhii/containers/blob/develop/src/Dictionary.php#L64) it is. It causes error in PHP 8.1+ and will cause a fatal error in PHP 9.
My guess it was just incidentally missing, and there is no intention behind missing return type.

**Comment by XedinUnknown** [comment]
Heya! Thanks for reporting this!

This looks to me like it was omitted for compatibility with PHP 5, where the implemented interface probably has no return type declared. Changing this may break that compatibility. That's not necessarily a show-stopper, but may mean that we need to signal end of support for some earlier PHP version.

**Comment by strangerkir** [comment]
Officially PHP 5 was never supported, as far as I understand. I can add a changelog entry about this (probably I had to add it anyway). Anything else I can do?

**Comment by XedinUnknown** [comment]
Just to be clear: Yep, I understand that PHP 5 is not supported; no need to mention that in the changelog. Just add a short description of what's changed, in the proper format, and that's all - LGTM :)
